### ISSUE TITLE
Thumbnail generation not working on subdirectory installation

### ISSUE THREAD

**Issue by nocturnenebula** [Ayemae/Grawlix-Webcomic-CMS#33] opened 2024-11-19 01:08 UTC
Hi, I'm running into a strange problem where thumbnails won't generate on an installation in a subdirectory. It's probably got something to do with Wordpress interfering (it's what I use to run the rest of the website) as always, but I'm not sure so I'd like to narrow things down.

I installed grawlix in the main directory of another website and the thumbnails worked fine, but when I installed it in a subdirectory of another website the thumbnails won't generate and the archive thumbnail generator doesn't work either (it just leads to my site's 404 page). This is the error that pops up whenever I try to generate a thumbnail on the comic's page (censored the subdirectory+server's name since it's private):

```php
Warning: imagejpeg(../SUBDIRECTORY/assets/images/comics/202411181646033997011/thumb.jpg): failed to open stream: No such file or directory in /home/SERVER/public_html/SUBDIRECTORY/_admin/inc/functions.inc.php on line 1601
``` 

I also followed the instructions for uncommenting RewriteBase and replacing the / with my subdirectory's name before anything, just to further narrow things down.

**Comment by eishiya** [comment] 2024-11-19 03:11
I wonder if that `SUBDIRECTORY/` should be in the thumbnail path... Since this is a path relative to the `_admin` directory (I think), `..` will take it into `SUBDIRECTORY` already, so it might be trying to save the file to `/home/SERVER/public_html/SUBDIRECTORY/SUBDIRECTORY/assets/images/comics/blah/thumb.jpg`.

I don't have a subdirectory install available to test with, would you be willing to try some things for me?
1. Print out the *absolute* path functions.inc.php, just before the `imagejpeg` line. The code for this would be
```php
echo realpath($destination_file);
```
The echoed string should appear at the top of the page. Does this absolute path include SUBDIRECTORY twice, or is it correct?

If it's in there twice, then the problem should be fixed by removing `.$milieu_list['directory']['value']` from these two lines:
https://github.com/Ayemae/Grawlix-Webcomic-CMS/blob/master/grawlix-cms/_admin/book.page-edit.php#L518
https://github.com/Ayemae/Grawlix-Webcomic-CMS/blob/master/grawlix-cms/_admin/inc/functions.inc.php#L1660

**Comment by nocturnenebula** [comment] 2024-11-19 17:08
Sorry just double-checking since I'm not really PHP savvy, but I put it here in functions.inc.php:
![image](https://github.com/user-attachments/assets/99cabb77-a295-413b-bbdc-77ad8054343d)

And try to regenerate the thumbnail, or is it supposed to appear in the comic page admin panel or the html of the page? I tried that-- hold up, after I cleared my cache and refreshed thumbnail regeneration worked. I don't know if that was supposed to be the fix or something but it worked.

**Comment by eishiya** [comment] 2024-11-19 18:57
The `echo` bit is correct in your screenshot. But just to clarify: you were supposed to do that and try to generate a screenshot, **without** making the other changes. The `echo` alone shouldn't change the functioning of the thumbnail generation, it would've just confirmed that the bug is what I think it was. The other changes were just for if it was indeed that bug.

Glad to hear it worked though! And whoops, good catch on the second removal being different from what I said - I was checking against a different version of Grawlix.

I will open a PR with these fixes, so that other people can benefit from them.

**Comment by eishiya** [comment] 2024-11-20 00:17
I forgot to ask: With this fix, do the thumbnails get *displayed* correctly wherever you're using them on your comic site?

**Comment by nocturnenebula** [comment] 2024-11-20 14:26
This is how they look on the website with the default theme:
![image](https://github.com/user-attachments/assets/890a33a9-a6de-4a29-81e4-6992571ba261)

These are the archive settings I used:
- Behavior: Single page
- Structure: Hierarchal
- Layout:
  - Markers: List
  - Pages: Grid
- Metadata: all options selected for testing (but I don't plan on using the Markers, and only plan to use Title, Date, and Thumbnail for Pages)


I also noticed today that thumbnails do not generate automatically, and have to be generated manually. Is this intentional or is it because I'm hosting my comic in a subdirectory? I also noticed the "Generate Archive Thumbnails" doesn't work still, too. 

I'm fine with generating thumbnails manually and never using that button but I know it wouldn't bode well for other people hosting their comic the way I am. Sorry if this is becoming a headache.

**Comment by eishiya** [comment] 2024-11-20 14:54
Thanks for testing that! Glad to see they work, even if I have no idea how 🤣

Thumbnails have to be generated manually, I believe. But, having never used thumbnails with Grawlix myself, I'm probably not the most informed person, but I don't recall seeing an option for automatic thumbnail generation in the panel or in the code.
(Honestly, if it were up to me, I'd remove the thumbnail feature entirely, I don't like page thumbnails in archives at all ;D But fortunately for others, it is not up to me.)

When you say "generate archive thumbnails" still doesn't work, do you mean you get the same error as before, or something different, or does it just not do anything?

**Comment by eishiya** [comment] 2024-11-20 16:07
You say it's "the same error", but you haven't mentioned a 404 page before. I could only test manually generating thumbnails (I have only someone else's live comic to test subdirectory installs with, can't go fouling up their hundreds of pages with thumbnails xP), and I just got the error you reported, no 404. Was this specific to mass-generating thumbnails? What sort of 404 page is this?

**Comment by nocturnenebula** [comment] 2024-11-20 20:49
Oh my bad, I thought I mentioned it in the original post. Sorry!! So this is the URL that I get when I use that button (site name censored):
```
DOMAIN.COM/_admin/book.archive.php?action=gen-thumbs
```

... Just now noticed it's missing the subdirectory's name all together.

**Comment by eishiya** [comment] 2024-11-21 00:23
Ah, this looks like a problem not with the thumbnail generating code (since that apparently still works; I assume this is with the fix from earlier?), but just with the link the button has. The other links (such as the manual thumbnail generation) work because they structure their URLs relative to the current page, but for some reason this one has the entire URL in it (but forgets the directory).

In `book.archive.php`, line 211-ish, find:
```php
$make_thumbs_output = "<a class='btn secondary' href='/_admin/book.archive.php?action=gen-thumbs'>Generate Archive Thumbnails</a>";
```
replace with:
```php
$make_thumbs_output = "<a class='btn secondary' href='?action=gen-thumbs'>Generate Archive Thumbnails</a>";
```
I'll amend my PR with this, and hopefully that's it for this bug.

**Comment by nocturnenebula** [comment] 2024-11-21 02:05
That did the trick! Thanks so much for helping me through this, I SUPER appreciate it!

**Comment by eishiya** [comment] 2024-11-21 03:36
Thank *you* for reporting this and helping me test my guesswork fixes :D

**Closed** 2024-11-21 16:35 UTC
